package com.example.user.projectbidanku.Model;

/**
 * Created by user on 09/11/2018.
 */

public class DataNamaBayi {
    public String[][] dataNama = {
            {"Abdad","Tekun beribadat","L","Arab"},
            {"Adelard","Gagah berani","L","Jerman"},
            {"Adelio","Pangeran mulia","L","Spanyol"},
            {"Adib","Budayawan","L","Arab"},
            {"Adiel","Hiasan","L","Arab"},
            {"Adli","Bijaksana","L","Turki"},
            {"Adney","Pulau bangsawan","L","Inggeris"},
            {"Adom","Bantuan dari Tuhan","L","Akan"},
            {"Adonis","Sangat menarik","L","Yunani"},
            {"Agni","Dewa api","L","India"},
            {"Aidan","Bersemangat","L","Irlandia"},
            {"Akash","Langit","L","Hindi"},
            {"Akemi","Senja hari","L","Jepang"},
            {"Akhdan","Sahabat","L","Arab"},
            {"Akins","Gagah berani","L","Yoruba"},
            {"Akmal","Sempurna","L","Arab"},
            {"Aksel","Tokoh perdamaian","L","Norwegia"},
            {"Albern","Bangsawan","L","Jerman"},
            {"Albern","Gagah berani","L","Jerman"},
            {"Alden","Pelindung yang bijaksana","L","Inggris"},
            {"Aldwin","Teman lama","L","Inggris"},
            {"Algis","Tombak","L","Jerman"},
            {"Alib","Yang lemah lembut","L","Arab"},
            {"Alvaro","Bijaksana","L","Spanyol"},
            {"Alvis","Mengetahui segalanya","L","Skandanavia"},
            {"Amanullah","Keamanan dari Tuhan","L","Arab"},
            {"Amato","Tercinta","L","Perancis"},
            {"Ames","Sahabat","L","Perancis"},
            {"Andros","Laut","L","Polandia"},
            {"Anjali","Penghormatan","L","Sansekerta"},
            {"Anjana","Perintah","L","Sansekerta"},
            {"Ansel","Orang suci","L","Perancis"},
            {"Antares","Raksasa","L","Yunani"},
            {"Anwar","Lebih jelas","L","Arab"},
            {"Apuila","Rajawali","L","Latin"},
            {"Araminta","Harum seperti bunga","L","Yunani"},
            {"Ararya","Golongan bangsawan","L","Sansekerta"},
            {"Archard","Sakti dan sangat kuat","L","Jerman"},
            {"Ardell","Tekun","L","Latin"},
            {"Ardhani","Suci","L","Sansekerta"},
            {"Arhab","Memanjakan","L","Arab"},
            {"Arnawama","Samudra","L","Sansekerta"},
            {"Arsa","Kegembiraan","L","Sansekerta"},
            {"Aruna","Merah","L","Sansekerta"},
            {"Arvin","Pengembala","L","Jerman"},
            {"Arvin","Sahabat","L","Jerman"},
            {"Aryasatya","Kemuliaan","L","Sansekerta"},
            {"Asadel","Kaya raya","L","Arab"},
            {"Asker","Prajurit","L","Turki"},
            {"Athalia","Tuhan yang Agung","L","Hawaii"},
            {"Atharwa","Mantra penolak bahaya","L","Sansekerta"},
            {"Atid","Matahari","L","Thailand"},
            {"Axelle","Sumber kehidupan","L","Perancis"},
            {"Aydin","Cerdas","L","Arab"},
            {"Azmi","Keteguhan hati","L","Arab"},
            {"Azzam","Kebulatan tekad","L","Arab"},
            {"Bahy","Yang tampan","L","Arab"},
            {"Balakosa","Kekuatan dan kejayaan","L","Sansekerta"},
            {"Balin","Prajurit kehormatan","L","Sansekerta"},
            {"Baluku","Beruang yang sangat kuat","L","Sansekerta"},
            {"Banjiro","Menikmati ketenangan","L","Jepang"},
            {"Baqir","Yang berilimu","L","Arab"},
            {"Bariq","Kemilau","L","Arab"},
            {"Barnes","Pekerja keras","L","Inggris"},
            {"Basil","Singa","L","Arab"},
            {"Bassam","Yang banyak tersenyum","L","Arab"},
            {"Bawika","Bermaksud baik","L","Sansekerta"},
            {"Bayanaka","Luar biasa","L","Sansekerta"},
            {"Bazyli","Raja","L","Polandia"},
            {"Bertin","Sahabat yang istimewa","L","Spanyol"},
            {"Berwin","Teman prajurit","L","Jerman"},
            {"Berwyn","Anak kesayangan","L","Inggris"},
            {"Berwyn","Teman yang setia","L","Inggris"},
            {"Bhadra","Selamat","L","Sansekerta"},
            {"Bhadrika","Gagah berani","L","Sansekerta"},
            {"Birney","Penghuni pulau","L","Anglo Saxon"},
            {"Blenda","Penuh kemewahan","L","Jerman"},
            {"Bonaro","Sahabat","L","Spanyol"},
            {"Bryna","Penuh kebajikan","L","Irlandia"},
            {"Buckley","Padang rumput rusa","L","Inggris"},
            {"Buntala","Tombak tajam","L","Sansekerta"},
            {"Byakta","Nampak nyata","L","Sansekerta"},
            {"Camilo","Sang pembebas","L","Latin"},
            {"Carlen","Sikuat","L","Jerman"},
            {"Carlene","Kuat","L","Jerman"},
            {"Carlin","Si juara kecil","L","Irlandia"},
            {"Carney","Kejayaan","L","Irlandia"},
            {"Carney","Pejuang","L","Irlandia"},
            {"Carola","Siap bertempur","L","Skotlandia"},
            {"Casey","Gagah berani","L","Irlandia"},
            {"Casimira","Pembawa perdamaian","L","Latin"},
            {"Catra","Payung kebesaran raja","L","Sansekerta"},
            {"Changyi","Terbuka dan bermurah hati","L","Cina"},
            {"Charemon","Semangat bergembira","L","Yunani"},
            {"Chiko","Panah","L","Jepang"},
            {"Clearesta","Puncak kemuliaan","L","Yunani"},
            {"Cleine","Terkenal","L","Yunani"},
            {"Cleon","Terkenal","L","Latin"},
            {"Cleosa","Terkenal","L","Yunani"},
            {"Clovis","Perajurit terkenal","L","Jerman"},
            {"Conan","Yang terkenal","L","Jerman"},
            {"Conary","Bijaksana","L","Sansekerta"},
            {"Cosmo","Harmoni","L","Yunani"},
            {"Curtina","Menyatukan","L","Sansekerta"},
            {"Dakari","Bahagia","L","Shona"},
            {"Danadyaksa","Penjaga kejayaan","L","Sansekerta"},
            {"Darpa","Kebanggaan","L","Sansekerta"},
            {"Darrell","Belahan jiwa","L","Perancis"},
            {"Darrell","Kekasih","L","Perancis"},
            {"Delmora","Laut","L","Latin"},
            {"Delvin","Teman yang biasa","L","Inggris"},
            {"Demas","Orang yang populer","L","Yunani"},
            {"Dennis","Dewa anggur","L","Yunani"},
            {"Deshi","Makmur","L","Cina"},
            {"Deven","Untuk Tuhan","L","Hindi"},
            {"Dhahir","Lembah yang indah","L","Arab"},
            {"Digdaya","Penakluk","L","Jawa"},
            {"Dimas (z)","Yang Terkasih","L","Jawa / Sansekerta"},
            {"Diwei","Berorientasi jelas","L","Cina"},
            {"Dobry","Baik hati","L","Polandia"},
            {"Donahue","Prajurit yang tangguh","L","Sansekerta"},
            {"Donatien","Hadiah","L","Perancis"},
            {"Dzakwan","Sangat cerdas","L","Arab"},
            {"Dzakwan","Harum semerbak","L","Arab"},
            {"Dzaky","Cerdas","L","Arab"},
            {"Edgina","Lahir untuk kaya","L","Teutic"},
            {"Edsel","Pemikirannya cermat","L","Anglo Saxon"},
            {"Ellard","Berani","L","Jerman"},
            {"Elroy","Milik raja","L","Perancis"},
            {"Elsdon","Bukit bangsawan","L","Inggris"},
            {"Elvia","Pemikirannya giat","L","Teutc"},
            {"Emery","peminpin yang baik hati","L","Jerman"},
            {"Enzi","Maha perkasa","L","Swahili"},
            {"Erasma","Hasrat","L","Yunani"},
            {"Eratus","Yang terkasih","L","Yunani"},
            {"Erland","Rajawali perkasa","L","Jerman"},
            {"Erling","Putra bangsawan","L","Inggris"},
            {"Ermina","Agung","L","Latin"},
            {"Erol","Gagah berani","L","Turki"},
            {"Ervanthe","Prajurit muda","L","Irlandia"},
            {"Evania","Penurut","L","Yunani"},
            {"Fadey","Keberanian","L","Slavia"},
            {"Farand","Menyenangkan","L","Yunani"},
            {"Farhan","Bergembira","L","Arab"},
            {"Farrell","Heroik","L","Irlandia"},
            {"Faste","Kokoh","L","Norwegia"},
            {"Fathi","Pembuka","L","Arab"},
            {"Fawwaz","Mendapat keberuntungan","L","Arab"},
            {"Felda","Ilham","L","Teutenik"},
            {"Fengying","Pintar dan cerdik","L","Cina"},
            {"Ferris","Sekeras batu karang","L","Celtik"},
            {"Filbert","Sangat pandai","L","Anglo Saxon"},
            {"Freda","Damai","L","Jerman"},
            {"Fredella","Pembawa kedamaian","L","Teutenik"},
            {"Frederika","Penuh kedamaian","L","Jerman"},
            {"Frodine","Teman yang bijaksana","L","Teutenik"},
            {"Gadi","Tuhan adalah penuntunku","L","Arab"},
            {"Galen","Tenang","L","Latin"},
            {"Galeno","Mendapat pencerahan","L","Sanyol"},
            {"Ganendra","Pasukan dewa","L","Sansekerta"},
            {"Gantari","Menyinari","L","Sansekerta"},
            {"Garwita","Bangga sekali","L","Sansekerta"},
            {"Gatawati","Telaga","L","Sansekerta"},
            {"Gavin","Garuda putih","L","Wales"},
            {"Gaviota","Burung camar","L","Spanyol"},
            {"Gavrila","Tuhan sumber kekuatanku","L","Ibrani"},
            {"Gene","Keturunan bangsawan","L","Yunani"},
            {"Gentala","Naga","L","Kawi"},
            {"Ghufron","Pengampunan","L","Arab"},
            {"Gladwin","Riang gembira","L","Inggris"},
            {"Godwin","Sahabat Tuhan","L","Inggris"},
            {"Gonza","Kasih sayang","L","Rutooro"},
            {"Gustin","Agung","L","Latin"},
            {"Gyala","Masa muda","L","Hungaria"},
            {"Habibi","Kesayanganku","L","Arab"},
            {"Hadrian","Laki-laki dari samudra","L","Latin"},
            {"Hagan","Pertahanan yang kokoh","L","Jerman"},
            {"Hagon","Awet muda","L","Irlandia"},
            {"Haidar","Pemberani","L","Arab"},
            {"Haidar","Singa","L","Arab"},
            {"Haldis","Bersemangat baja","L","Teutenik"},
            {"Haley","Pribumi","L","Inggris"},
            {"Hali","Laut","L","Yunani"},
            {"Hamdan","Yang banyak pujian","L","Arab"},
            {"Hamdi","Pujian","L","Arab"},
            {"Hanbal","Murni","L","Arab"},
            {"Handaru","Meteor","L","Kawi"},
            {"Hansa","Angsa","L","Sansekerta"},
            {"Haocun","Agung","L","Cina"},
            {"Hara","Untaian mutiara","L","Sansekerta"},
            {"Harding","Putera sang pemberani","L","Inggris"},
            {"Harina","Kijang","L","Kawi"},
            {"Haruni","Puncak","L","Afrika"},
            {"Hector","Tabah","L","Yunani"},
            {"Hedona","Cahaya yang terang","L","Yunani"},
            {"Hermes","Pembawa pesan","L","Yunani"},
            {"Herwit","Sangat cerdik","L","Jerman"},
            {"Hesperos","Bintang timur","L","Jerman"},
            {"Hieu","Terhormat","L","Vietnam"},
            {"Hillel","Bulan baru","L","Arab"},
            {"Hiromasa","Adil","L","Jepang"},
            {"Hisyam","Kemurahan","L","Arab"},
            {"Honesto","Jujur","L","Pilipina"},
            {"Hongli","Sekeras karang","L","Cina"},
            {"Hototo","Hakim","L","Amerika asli"},
            {"Huanran","Punya watak riang","L","Cina"},
            {"Huga","Intelek","L","Teutenik"},
            {"Humam","Besar ambisinya","L","Arab"},
            {"Hylmi","Penyabar","L","Arab"},
            {"Imad","Arus utama","L","Arab"},
            {"Iniko","Lahir dimasa sulit","L","Ibo"},
            {"Ipyana","Murah hati","L","Nyakusa"},
            {"Ivander","Laki -laki yang terbaik","L","Ibrani"},
            {"Jabulani","Bahagia","L","Shona"},
            {"Jareb","Perjuangan","L","Yahudi"},
            {"Jarvis","Ahli menggunakan tombak","L","Jermasn"},
            {"Jauhar","Permata","L","Arab"},
            {"Javas","Cekatan","L","Sansekerta"},
            {"Jawad","Pemurah","L","Arab"},
            {"Jayasri","Kemenangan yang cemerlang","L","Sansekerta"},
            {"Jerolin","Suci","L","Latin"},
            {"Jevera","Kehidupan","L","Ibran"},
            {"Jianheeng","Gigih dan tabah","L","Cina"},
            {"Jianying","Giat dan penting","L","Cina"},
            {"Jiazhen","Melestarikan bisnis keluarga","L","Cina"},
            {"Jierui","Berpikir cepat","L","Cina"},
            {"Jili","Sukses dalam karir","L","Cina"},
            {"Jingmi","Menghargai orang","L","Cina"},
            {"Jivin","Pencari nafkah","L","Hindi"},
            {"Joachim","Tuhan akan menentukan","L","Yahudi"},
            {"Jomei","Sinar yang menyebar","L","Jepang"},
            {"Jorell","Dia yang menyelamatkan","L","Amerika"},
            {"Juro","Harapan terbaik","L","Jepang"},
            {"Justis","Tidak berat sebelah","L","Perancis"},
            {"Juvenal","Anak muda","L","Latin"},
            {"Kaemon","Riang gembira","L","Jepang"},
            {"Kahraman","Pahlawan","L","Turki"},
            {"Kaibo","Berpengetahuan luas","L","Cina"},
            {"Kaili","Mendambakan kemakmuran","L","Cina"},
            {"Kaipo","Kekasih","L","Hawai"},
            {"Kalani","Surga","L","Hawai"},
            {"Kalpana","Tercipta","L","Kawi"},
            {"Kamau","Perajurit yang perkasa","L","Kikiyu"},
            {"Kamazu","Obat","L","Nguni"},
            {"Kangjian","Murah hati dan tegap","L","Cina"},
            {"Kapono","Adil","L","Hawai"},
            {"Kara","Sinar cahaya","L","Sansekerta"},
            {"Kasimir","Tenteram","L","Arab"},
            {"Kastara","Termashur","L","Sansekerta"},
            {"Kasyapi","Bumi","L","Sansekerta"},
            {"Kawindra","Rajanya pujangga","L","Sansekerta"},
            {"Kayana","Dermawan","L","Sansekerta"},
            {"Kayle","Anjing yang bisa dipercaya","L","Yahudi"},
            {"Kendrick","Kepala istana","L","Skotlandia"},
            {"Kennard","Kapten yang gagah berani","L","Irlandia"},
            {"Kentaro","Laki-laki dewasa","L","Jepang"},
            {"Kenward","Berani","L","Inggris"},
            {"Kenzie","Peminpim yang bijaksana","L","Sansekerta"},
            {"Keola","Kehidupan","L","Hawai"},
            {"Khairullah","Kebaikan dari Allah","L","Arab"},
            {"Khalil","Kesayanganku","L","Arab"},
            {"Khalish","Murni","L","Arab"},
            {"Khazhim","Dapat mengekang amarah","L","Arab"},
            {"Laksita","Terkenal","L","Sansekerta"},
            {"Lamont","Ahli hokum","L","Sansekerta"},
            {"Lander","Manusia singa","L","Basqua"},
            {"Landry","Penguasa","L","Perancis"},
            {"Langundo","Tenang","L","Amerika"},
            {"Larrimore","Pembuat baju besi","L","Perancis"},
            {"Laszlo","Penguasa yang terkenal","L","Hungaria"},
            {"Lateef","Menyenangkan","L","Arab"},
            {"Lauda","Pujian","L","Latin"},
            {"Lavina","Sinar yang terang","L","Inggris"},
            {"Lawana","Samudra","L","Kawi"},
            {"Layana","Mengalir terus","L","KawI"},
            {"Leif","Kepercayaan","L","Old Norse"},
            {"Leroy","Raja","L","Perancis"},
            {"Leverrett","Kelinci muda","L","Perancis"},
            {"Lian","Tenang dan masuk akal","L","Cina"},
            {"Liangyi","Baik dan ramah","L","Cina"},
            {"Liiu Yaoshan","Terhormat","L","Cina"},
            {"Liu Changhai","Melimpah seperti laut","L","Cina"},
            {"Liu Xingsheng","Makmur dan melimpah ruah","L","Cina"},
            {"Luthfi","Lembut","L","Arab"},
            {"Mackinnley","Putera penguasa","L","Irlandia"},
            {"Magnus","Agung","L","Latin"},
            {"Mahadri","Gunung besar","L","Kawi"},
            {"Mahasura","Pejuang besar","L","Kawi"},
            {"Mahawira","Pahlawan besar","L","Kawi"},
            {"Maheswara","Raja besar","L","Kawi"},
            {"Mahib","Orang yang karismatik","L","Arab"},
            {"Mahija","Putra bumi","L","Sansekerta"},
            {"Mahrus","Yang dijaga","L","Arab"},
            {"Majdi","Kemuliaan","L","Arab"},
            {"Makarim","Bersifat mulia","L","Arab"},
            {"Maknar","Kuat","L","Norwegia"},
            {"Manuela","Tuhan beserta kita","L","Ibrani"},
            {"Manyura","Burung merak","L","Kawi"},
            {"Marlen","Burung elang","L","Anglo Saxon"},
            {"Marva","Sungguh indahy","L","Latin"},
            {"Masao","Kebenaran","L","Jepang"},
            {"Masato","Keadilan","L","Jepang"},
            {"Maska","Maha perkasa","L","Amerika Asli"},
            {"Masou","Api Tuhan","L","Amerika Asli"},
            {"Mas’ud","Bahagia","L","Arab"},
            {"Maynard","Maha perkasa","L","Inggris"},
            {"Melvin","Sobat kental","L","Inggris"},
            {"Moria","Pilihan Tuham","L","Yunani"},
            {"Moza","Air Anggur","L","Latin"},
            {"Mubarak","Yang diberkati","L","Arab"},
            {"Mudrik","Berakal","L","Arab"},
            {"Mufrih","Orang yang membuat gembira","L","Arab"},
            {"Mugisa","Beruntung","L","Rutooro"},
            {"Muhana","Tenang","L","Arab"},
            {"Muhana","Damai","L","Arab"},
            {"Muhsin","Yang berbuat kebaikan","L","Arab"},
            {"Mukasa","Orang kepercayaan Tuhan","L","Uganda"},
            {"Mukhbit","Tunduk patuh","L","Arab"},
            {"Muntashir","Yang menang","L","Arab"},
            {"Mus’ad","Yang dibahagiaakan","L","Arab"},
            {"Mushoddiq","Yang mempercayai","L","Arab"},
            {"Mustajab","Terkabul doanya","L","Arab"},
            {"Mutawakkil","Yang bertawakal","L","Arab"},
            {"Nabiha","Cerdas/Cerdik","L","Arab"},
            {"Naeem","Mempesona","L","Arab"},
            {"Nararya","Yang dimuliakan","L","Sansekerta"},
            {"Narda","Kebahagiaan","L","Yunani"},
            {"Naryama","Pemimpin","L","Kawi"},
            {"Nash","Karang yang terjanl","L","Inggris"},
            {"Nashif","Adil","L","Arab"},
            {"Naufal","Dermawan","L","Arab"},
            {"Nawwar","Pemberi cahaya","L","Arab"},
            {"Nirwasita","Bijaksana","L","Sansekerta"},
            {"Niscala","Kokoh","L","Sansekerta"},
            {"Nismara","Penuh ketenangan","L","Kawi"},
            {"Nitisara","Bijaksana","L","Kawi"},
            {"Nohan","Merasa bahagia","L","Kawi"},
            {"Obadiah","Abdi Tuhan","L","Ibrani"},
            {"Odelia","Pewaris","L","Yunani"},
            {"Odell","Melodi","L","Yunani"},
            {"Okechuku","Pemberian Tuhan","L","Ibo"},
            {"Olubayo","Kebahagian yang tak terkira","L","Yoruba"},
            {"Ophir","Dapat dipercaya","L","Yahudi"},
            {"Oriana","Keemasan","L","Latin"},
            {"Orlando","Terkenal ke penjuru negeri","L","Jerman"},
            {"Osahar","Tuhan maha mendengar","L","Beninn"},
            {"Osborn","Beruang yang sangat kuat","L","Sansekerta"},
            {"Osmond","Pelindung yang perkasa","L","Inggris"},
            {"Osric","Penguasa yang terkenal","L","Inggris"},
            {"Oswald","Kekuasaan Tuhan","L","Inggris"},
            {"Otadan","Berlimpah ruah","L","Amerika Asli"},
            {"Ozora","Kekuatan dari Tuhan","L","Ibrani"},
            {"Parama","Paling unggul","L","Sansekerta"},
            {"Partaya","Yang terpercaya","L","Kawiw"},
            {"Pastika","Kristal","L","Sansekerta"},
            {"Pawana","Angin","L","Kawi"},
            {"Penrod","Komandan yang terkenal","L","Jerman"},
            {"Philemon","Ciuman","L","Yunani"},
            {"Pirata","Jiwa","L","Kawi"},
            {"Pragata","Cepat","L","Kawi"},
            {"Prawara","Paling terkemuka","L","Sansekerta"},
            {"Prayata","Bersifat saleh","L","Sansekerta"},
            {"Qibo","Berbakat langka, haus ilmu","L","Cina"},
            {"Qosiim","Yang molek","L","Arab"},
            {"Quentin","Mendambakan masa depan","L","Cina"},
            {"Quinlan","Berperawakan yang bagus","L","Irlandia"},
            {"Quon","Cerdas","L","Cina"},
            {"Quon","Terang","L","Cina"},
            {"Radithya","Matahari","L","Sansekerta"},
            {"Radmila","Bekerja untuk rakyat","L","Sansekerta"},
            {"Radoslaw","Kejayaan yang gemilang","L","Polandia"},
            {"Rafif","Berahklak baik","L","Arab"},
            {"Raissa","Yang beriman","L","Perancis"},
            {"Rania","Bangsawan","L","Sansekerta"},
            {"Ranjana","Bergembira","L","Kawi"},
            {"Reseda","Sembuh","L","Latin"},
            {"Reynard","Bijaksana","L","Perancis"},
            {"Riona","Santo","L","Irlandia"},
            {"Riordan","Penyair istana","L","Inggris"},
            {"Rizqullah","Rezki dari Allah","L","Arab"},
            {"Roid","Pemimpin","L","Arab"},
            {"Roland","Terkenal sepanjang negeri","L","Jerman"},
            {"Ruhakana","Pandai berdebat","L","Rukiga"},
            {"Runako","Tampan","L","Shona"},
            {"Ruobai","Lurus seperti pohon cemara","L","Cina"},
            {"Sadajiwa","Hidup selamanya","L","Sansekerta"},
            {"Sadina","Pemilik kebaikan","L","Sansekerta"},
            {"Sadubi","Budinya sangat luhur","L","Kawi"},
            {"Saguna","Memiliki sufat baik","L","Kawi"},
            {"Saktika","Kekuasaan spritual","L","Kawi"},
            {"Samana","Nafas hidup","L","Sansekerta"},
            {"Samih","Lemah lembut","L","Arab"},
            {"Samitra","Berteman","L","Sansekerta"},
            {"Sandya","Persatuan","L","Sansekerta"},
            {"Sarkara","Madu","L","Sansekerta"},
            {"Sava","Ketenangan","L","Ibrani"},
            {"Shadiq","Tulus kecintaannya","L","Arab"},
            {"Shaosheng","Keluarga makmur","L","Cina"},
            {"Shbouh","Mulia","L","Armenia"},
            {"Sherwin","Teman sejati","L","Anglo Saxon"},
            {"Shilin","Intelek","L","Cina"},
            {"Shobir","Penyabar","L","Arab"},
            {"Shunnar","Menyenangkan","L","Arab"},
            {"Sigra","Bertindak cepat","L","Kawi"},
            {"Sulthanah","Pemimpin wanita","L","Arab"},
            {"Supala","Menghasilkan buah yang baik","L","Sansekerta"},
            {"Surur","Kegembiraan","L","Arab"},
            {"Syandana","Mengalir terus","L","Sansekerta"},
            {"Syuja’","Pemberani","L","Arab"},
            {"Tadya","Tertip","L","Sansekerta"},
            {"Taksa","Sayap","L","Kawi"},
            {"Tamim","Orang yang kuat","L","Arab"},
            {"Taoran","Bahagia dan riang","L","Cina"},
            {"Taqi","Bertaqwa","L","Arab"},
            {"Tauhid","Kemurnian iman","L","Arab"},
            {"Teripta","Kepuasan","L","Sansekerta"},
            {"Thahir","Bersih","L","Arab"},
            {"Theobald","Pangeran","L","Jerman"},
            {"Tianlun Le","Keluarga bahagia","L","Cina"},
            {"Tibra","Kuat dan keras","L","Sansekerta"},
            {"Tobias","Tuhan maha sempurna","L","Yahudi"},
            {"Tong mu","Baik budi dan ramah","L","Cina"},
            {"Toshi-Shitas","Yang lebih muda","L","Jepang"},
            {"Toyadi","Samudra","L","Sansekerta"},
            {"Trina","Murni","L","Yunani"},
            {"Tristan","Gagah berani","L","Wales"},
            {"Trygve","Pemenang yang gagah berani","L","Norwegia"},
            {"Tsabat","Keteguhan hati","L","Arab"},
            {"Tsaqib","Tajam pemikiran","L","Arab"},
            {"Tsary","Hartawan","L","Arab"},
            {"Tuoli","Pemikir cerdik","L","Cina"},
            {"Tyaga","Pemberian Tuhan","L","Kawi"},
            {"Ubadah","Berbakti kepada Tuhan","L","Arab"},
            {"Uistean","Pandai berdebat","L","Irlandia"},
            {"Urdha","Mulia","L","Sansekerta"},
            {"Vania","Anugerah yang sejati","L","Ibrani"},
            {"Vegard","Mahligai","L","Norwegia"},
            {"Velma","Perlindungan","L","Jerman"},
            {"Vincent","Penakluk","L","Latin"},
            {"Wadi","Yang tenang","L","Arab"},
            {"Wadud","Yang dicintai","L","Arab"},
            {"Wajendra","Raja","L","Kawi"},
            {"Wajih","Orang yang berkedudukan","L","Arab"},
            {"Walmond","Penguasa perkasa","L","Jerman"},
            {"Wang Chunying","Berpengetahuan luas","L","Cina"},
            {"Wang Dunrui","Pintar dan cerdas","L","Cina"},
            {"Wang Wenxiao","Pintar dalam segala bidang","L","Cina"},
            {"Wang Xiaohui","Cerdas dan berwawasan","L","Cina"},
            {"Wang Xuemin","Punya pikiran luas","L","Cina"},
            {"Wang Xuesi","Belajar dan berpikir","L","Cina"},
            {"Wang Zeming","Berwawasan luas","L","Cina"},
            {"Wangting","Melestarikan kemakmuran keluarga","L","Cina"},
            {"Waradana","Hadiah yang bernilai","L","Sansekerta"},
            {"Wasim","Rupawan","L","Arab"},
            {"Wastu","Berharta benda","L","Sansekerta"},
            {"Weida","Dilahirkan dengan berkualitas","L","Cina"},
            {"Weiheng","Bertekad bulat","L","Cina"},
            {"Wenhua","Berbudaya","L","Cina"},
            {"Wilasa","Kesenangan","L","Sansekerta"},
            {"Wirasana","Bersikap pahlawan","L","Sansekerta"},
            {"Wirasena","Kumpulan pemberani","L","Kawi"},
            {"Wistara","Jelas dan pandai","L","Sansekerta"},
            {"Wursita","Terhormat","L","Kawi"},
            {"Xabat","Juruselamat","L","Basqua"},
            {"Xingguang Zhao","Disinari bintang mulia","L","Cina"},
            {"Yasykur","Bersyukur","L","Arab"},
            {"Yatha","Menurut","L","Sansekerta"},
            {"Yelu","Pewaris keluarga makmur","L","Cina"},
            {"Yodha","Pejuang besar","L","Kawi"},
            {"Yongsheng","Punya ambisi jelas","L","Cina"},
            {"Yuwen","Terkenal seluruh dunia","L","Cina"},
            {"Zahid","Rendah hati","L","Arab"},
            {"Zhafif","Cerdik","L","Arab"},
            {"Zhafir","Orang yang menang","L","Arab"},
            {"Zhang Bingjie","Sesuci kristal","L","Cina"},
            {"Zhang Jiangwu","Ramping","L","Cina"},
            {"Zhang Junda","Anggun dan sangat sopan","L","Cina"},
            {"Zhang Junqing","Tampan penuh vitalitas","L","Cina"},
            {"Zhang Xiuhuan","Tampan dan penuh sprit","L","Cina"},
            {"Zhang Xuemei","Halus seperti bunga zahib","L","Cina"},
            {"Zhaoyang Hong","Matahari terbit cerah","L","Cina"},
            {"Zhuting","Orang penting","L","Cina"},
            {"Ziskind","Anak yang manis","L","Yahudi"},
            {"Zohar","Cahaya terang","L","Yahudi"},
            {"Zuhayr","Bercahaya","L","Arab"},
            {"Aabidah","Tekun beribadah","P","Arab"},
            {"Aathifah","Pemberian","P","Arab"},
            {"Abdiel","Hamba Allah","P","Ibrani"},
            {"Abidah","Beradab","P","Arab"},
            {"Adara","Cantik","P","Yunani"},
            {"Adawiyah","Seorang wanita sufi","P","Arab"},
            {"Adelia","Mulia","P","Jerman"},
            {"Adena","Indah","P","Yunani"},
            {"Adira","Kuat","P","Yahudi"},
            {"Adonia","Cantik","P","Spanyol"},
            {"Adoria","Tercinta","P","Latin"},
            {"Adora","Yang tercinta","P","Latin"},
            {"Adrienne","Kaya","P","Perancis"},
            {"Adsila","Berbunga","P","Amerika asli"},
            {"Afrah","Kegembiraan","P","Arab"},
            {"Aiko","Tercinta","P","Jepang"},
            {"Aimee","Tercinta","P","Perancis"},
            {"Ainiyah","Pohon rimbun bersemi","P","Arab"},
            {"Alana","Damai","P","Irlandia"},
            {"Alanza","Ambisius","P","Spanyol"},
            {"Alifah","Ramah tamah","P","Arab"},
            {"Alina","Terang","P","Slavia"},
            {"Aline","Jujur","P","Skotlandia"},
            {"Alisha","Mulia","P","Jerman"},
            {"Almasah","Batu mulia","P","Arab"},
            {"Almeta","Ambisius","P","Latin"},
            {"Alvina","Sahabat","P","Inggris"},
            {"Amabel","Baik hati","P","Latin"},
            {"Amada","Tersayang","P","Spanyol"},
            {"Amandla","Tersayang","P","Afrika"},
            {"Amany","Cita-cita","P","Arab"},
            {"Amany","Harapan","P","Arab"},
            {"Ambrose","Abadi","P","Ibrani"},
            {"Aminah","Dapat dipercaya","P","Arab"},
            {"Amira","Ungkapan","P","Yahudi"},
            {"Amira","Putri bangsawan","P","Arab"},
            {"Anevay","Pemimpin","P","Amerika"},
            {"Anisah","Teman penghibur","P","Arab"},
            {"Anisah","Lemah lembut","P","Arab"},
            {"Annora","Cahaya","P","Yunani"},
            {"Anthea","Bunga","P","Yunani"},
            {"Anthea","Dewi kebajikan","P","Ibrani"},
            {"Antonite","Remaja","P","Yunani"},
            {"Anya","Penuh keagungan","P","Ibrani"},
            {"Ardelle","Sangat antusias","P","Latin"},
            {"Ardelle","Hangat","P","Latin"},
            {"Ardelle","Tekun","P","Amerika asli"},
            {"Ardith","Kebun bunga","P","Yahudi"},
            {"Areta","Gadis yang bijak","P","Yunani"},
            {"Ariane","Kudus","P","Perancis"},
            {"Arij","Bau yang sedap","P","Arab"},
            {"Ariti","Perunggu","P","Sansekerta"},
            {"Armila","Gelang","P","Latin"},
            {"Asahy","Warna-warni","P","Arab"},
            {"Ascarya","Tampil kedepan","P","Sansekerta"},
            {"Athifa","Lemah lembut","P","Arab"},
            {"Audrey","Mulia","P","Perancis"},
            {"Aurelia","Makmur","P","Latin"},
            {"Aurelia","Bahagia","P","Latin"},
            {"Austrin","Agung","P","Latin"},
            {"Avisa","Perawan yang lembut","P","Latin"},
            {"Awahita","Penuh perhatian","P","Sansekerta"},
            {"Ayana","Berbunga","P","Amerika asli"},
            {"Azalia","Yang dilindungi","P","Ibrani"},
            {"Azana","Megah","P","Afrika"},
            {"Azhar","Bunga-bunga","P","Arab"},
            {"Azighah","Memancar","P","Arab"},
            {"Bahijah","Sukaria","P","Arab"},
            {"Bahirah","Disegani orang","P","Arab"},
            {"Bari’ah","Cantik","P","Arab"},
            {"Bashirah","Berakal","P","Arab"},
            {"Basilia","Ratu Agung","P","Yunani"},
            {"Basimah","Selalu tersenyum","P","Arab"},
            {"Basyirah","Kabar kegembiraan","P","Arab"},
            {"Basyirah","Pemberi kabar gembira","P","Arab"},
            {"Belicia","Abdi Tuhan","P","Spanyol"},
            {"Belva","Purnama yang indah","P","Amerika asli"},
            {"Belva","Jujur","P","Latin"},
            {"Berly","Mutiara hijau lautan","P","Yunani"},
            {"Bernessa","Pemberani","P","TeutIc"},
            {"Beryl","Permata yang berharga","P","Ibrani"},
            {"Blythe","Bahagia","P","Inggris"},
            {"Burairah","Berbuat baik","P","Arab"},
            {"Cadudasa","Cemerlang","P","Sansekerta"},
            {"Callysta","Kecantikan yang luar biasa","P","Yunani"},
            {"Calya","Tanpa cacat","P","Sansekerta"},
            {"Candida","Putih terang","P","Latin"},
            {"Carissa","Anggun","P","Yunani"},
            {"Cascata","Air terjun","P","Italia"},
            {"Cathilin","Mata yang indah","P","Celtik"},
            {"Catriona","Murni sejati","P","Celtik"},
            {"Celena","Bintang","P","Yunani"},
            {"Celesta","Surga","P","Latin"},
            {"Celestyn","Surga","P","Latin"},
            {"Cetta","Berpengetahuan luas","P","Sansekerta"},
            {"Charis","Anggun","P","Yunani"},
            {"Chastine","Murni sejati","P","Latin"},
            {"Chenoa","Burung merpati putih","P","Amerika asli"},
            {"Chesna","Tenteram","P","Slavia"},
            {"Chiara","Terkenal","P","Italia"},
            {"Chindaga","Pandan wangi","P","Sansekerta"},
            {"Chumani","Titik-titik embun","P","Lakota"},
            {"Cicely","Musik","P","Latin"},
            {"Cira","Matahari","P","Italia"},
            {"Clarance","Sangat terkenal","P","Latin"},
            {"Clarinta","Sikecil yang termashur","P","Latin"},
            {"Cleonima","Nama yang jaya","P","Yunani"},
            {"Clianta","Bunga kemenangan","P","Yunani"},
            {"Clorinda","Terkenal karena Kecantikannya","P","Latin"},
            {"Cloris","Bunga yang wangi","P","Latin"},
            {"Cmille","Keagungan","P","Latin"},
            {"Concordia","Harmoni","P","Latin"},
            {"Concordia","Selaras","P","Latin"},
            {"Cordelia","Hangat","P","Latin"},
            {"Cordelia","Baik hati","P","Latin"},
            {"Cottina","Mahkota bunga","P","Yunani"},
            {"Cyma","Keanggunan","P","Ibrani"},
            {"Dagna","Bersinar-sinar","P","TeutIc"},
            {"Dahayu","Cantik","P","Sansekerta"},
            {"Daiva","Dewa","P","Sansekerta"},
            {"Daksayini","Dewi padi","P","Sansekerta"},
            {"Daliyah","Pohon anggur","P","Arab"},
            {"Damara","Gadisyang cantik","P","Yunani"},
            {"Damita","Bangsawan kecil","P","Spanyol"},
            {"Danah","Batu mulia","P","Arab"},
            {"Danakitri","Kemasyuran","P","Sansekerta"},
            {"Danella","Istri yang bijaksana","P","TeutIc"},
            {"Darda","Mutiara kebijaksanaan","P","Ibrani"},
            {"Darlene","Yang sangat dicintai","P","Anglo Saxon"},
            {"Davu","Awal","P","Africa"},
            {"Dayita","Kekasih","P","Sansekerta"},
            {"Deana","Surga","P","Latin"},
            {"Deana","Kahyangan","P","Latin"},
            {"Demetria","Penutup bumi","P","Yunani"},
            {"Deron","Milik Tuhan","P","Armenia"},
            {"Devin","Puisi","P","Irlandia"},
            {"Didrika","Pemimpin","P","Jerman"},
            {"Dihyan","Matahari","P","Sansekerta"},
            {"Dolores","Sedih","P","Spanyol"},
            {"Dongsheng","Matahari terbit","P","Cina"},
            {"Dorinda","Hadiah","P","Spanyol"},
            {"Durriyah","Cahaya mutiara","P","Arab"},
            {"Dyani","Rusa","P","Amerika asli"},
            {"Earlene","Wanita yang agung","P","Anglo. Saxon"},
            {"Eldora","Hadiah kebijaksanaan","P","Anglo Saxon"},
            {"Eleanor","Cahaya","P","Yunani"},
            {"Elfreda","Agung dan bijaksana","P","Jerman"},
            {"Elfrida","Damai","P","Jerman"},
            {"Elfrida","Tentram","P","Jerman"},
            {"Elma","Buah yang manis","P","Turki"},
            {"Elora","Terang","P","Yunani"},
            {"Elpida","Harapan","P","Ibrani"},
            {"Elvaretta","Kebajikan","P","Teutic"},
            {"Elvina","Ramah dan bijaksana","P","Teutc"},
            {"Elysia","Dari surga","P","Yunani"},
            {"Engrasia","Anggun","P","Latin"},
            {"Erlinda","Lincah","P","Ibrani"},
            {"Ethana","Kuat","P","Yahudi"},
            {"Eustacia","Subur","P","Yunani"},
            {"Evanthe","Bunga yang indah","P","Yunani"},
            {"Faadhilah","Yang mulia","P","Arab"},
            {"Fadhilah","Kemuliaan","P","Arab"},
            {"Fakhirah","Kebanggaan","P","Arab"},
            {"Fakinah","Buah","P","Arab"},
            {"Fallon","Cucu penguasa","P","Irlandia"},
            {"Farhanah","Bergembira","P","Arab"},
            {"Farica","Penuh kedamaian","P","Jerman"},
            {"Fathinah","Cerdas","P","Arab"},
            {"Fausta","Keberuntungan","P","Latin"},
            {"Faustine","Beruntung","P","Latin"},
            {"Fauziyyah","Yang beruntung","P","Arab"},
            {"Fawnia","Yang berharga","P","Anglo Saxon"},
            {"Fayola","Beruntung","P","Nigeria"},
            {"Fedora","Pemberian Tuhan","P","Yunani"},
            {"Fengguang","Bersemangat menyala-nyala","P","Cina"},
            {"Feodora","Anugerah Tuhan","P","Yunani"},
            {"Fidela","Wanita yang jujur","P","Latin"},
            {"Fidelya","Bisa dipercaya","P","Prancis"},
            {"Filia","Peminpin yang baik hati","P","Ibrani"},
            {"Fiorenza","Bunga","P","Italia"},
            {"Fredelina","Bijaksana","P","Teutenik"},
            {"Frieda","Perdamaian","P","Jerman"},
            {"Fruma","Satu iman","P","Ibrani"},
            {"Galena","Penyembuh penyakit","P","yunani"},
            {"Gaoqi","Berintegritas tinggi","P","Cina"},
            {"Gaozhan","Berwawasan bagus","P","Cina"},
            {"Garini","Istiri yang baik","P","Kawi"},
            {"Garneta","Permata merah","P","Latin"},
            {"Ghadah","Wanita yang lembut","P","Arab"},
            {"Gilda","Berselimut emas","P","Inggris"},
            {"Grania","Cinta yang mesra","P","Celtik"},
            {"Grimonia","Wanita yang patut dimuliakan","P","Latin"},
            {"Griselda","Gadis yang gigih","P","Teutenik"},
            {"Habibah","Kekasih","P","Arab"},
            {"Habibah","Tersayang","P","Arab"},
            {"Habibah","Kesayanganku","P","Arab"},
            {"Hafidhah","Pemelihara","P","Arab"},
            {"Haibah","Berwibawa","P","Arab"},
            {"Haiyun","Berbudi mulia","P","Cina"},
            {"Hakimah","Arif dan bijaksana","P","Arab"},
            {"Halona","Beruntung","P","Amerika asli"},
            {"Hamamah","Burung merpati","P","Arab"},
            {"Hamilah","Sabar dan berakal","P","Arab"},
            {"Hana’","Kekayaan tanpa payah","P","Arab"},
            {"Hanan","Kasih sayang","P","Arab"},
            {"Hanan","Kelembutan hati","P","Arab"},
            {"Hannah","Penuh keagungan","P","Ibrani"},
            {"Haruko","Kelahiran pertama","P","Jepang"},
            {"Hasna","Cantik","P","Arab"},
            {"Hasna","Molek","P","Arab"},
            {"Hauda","Burung kasuari","P","Arab"},
            {"Hazimzh","Wanita yang sangat teliti","P","Arab"},
            {"Hedva","Kegembiraan","P","Ibrani"},
            {"Hedy","Manis","P","Yunani"},
            {"Hedy","Menyenangkan","P","Inggeris"},
            {"Helga","Alim","P","Jerman"},
            {"Helga","Saleh","P","Sansekerta"},
            {"Helga","Suci","P","Jerman"},
            {"Helonia","Bunga bakung","P","Yunani"},
            {"Helsa","Diberikan pada Tuhan","P","Ibrani"},
            {"Hepziba","Kecintaan","P","Ibrani"},
            {"Hindun","Sahabat wanita","P","Arab"},
            {"Hira","Intan","P","Sansekerta"},
            {"Honora","Yang terhormat","P","Latin"},
            {"Hoshi","Bintang","P","Jepang"},
            {"Hoshiko","Bintang","P","Jepang"},
            {"Huajin","Bermoral mulia","P","Cina"},
            {"Huberta","Berjiwa terang","P","Tutenik"},
            {"Huriyah","Bidadari surga","P","Arab"},
            {"Huriyah","Wanita yang cantik","P","Arab"},
            {"Huwaida","Lemah lembut","P","Arab"},
            {"Ibtisamah","Senyum","P","Arab"},
            {"Inas","Baik hati","P","Arab"},
            {"Indurasmi","Sinar rembulan","P","Sansekerta"},
            {"Iolana","Meluncur seperti elang","P","Hawai"},
            {"Irmadel","Gadis bangsawan","P","Teutenik"},
            {"Isadora","Dewi tertinggi","P","Latin"},
            {"Isaura","Udara yang sejuk","P","Yunani"},
            {"Jacinda","Cantik dan menarik","P","Yunani"},
            {"Jamilah","Cantik rupawan","P","Arab"},
            {"Janitra","Berderajat tinggi","P","Sansekerta"},
            {"Jauharah","Mutiara","P","Arab"},
            {"Jauza","Bntang gemini","P","Arab"},
            {"Jawahir","Mutiara","P","Arab"},
            {"Jeconia","Hadiah dari Tuhan","P","Ibrani"},
            {"Jiaya","Lemah gemulai","P","Cina"},
            {"Jibon","Kehidupan","P","Hindi"},
            {"Jimi","Pengganti","P","Yahudi"},
            {"Jingyi","Bersikap terpuji","P","Cina"},
            {"Jinxiu","Masa depan gemilang","P","Cina"},
            {"Jonea","Keagungan","P","Ibrani"},
            {"Jovita","Periang","P","Latin"},
            {"Jovita","Baik hati","P","Latin"},
            {"Jovita","Kebahagian","P","Latin"},
            {"Julinka","Kelihatan muda","P","Hungaria"},
            {"Juman","Mutiara","P","Arab"},
            {"Jun","Kebenaran","P","Cina"},
            {"Justine","Adil","P","Latin"},
            {"Kagami","Cermin","P","Jepang"},
            {"Kaia","Bumi","P","Yunani"},
            {"Kaila","Mahkota","P","Yunani"},
            {"Kalani","Langit","P","Hawai"},
            {"Kalani","Kepala suku","P","Hawai"},
            {"Kalea","Terang","P","Hawai"},
            {"Kalei","Rangkaian bunga","P","Hawai"},
            {"Kalena","Murni","P","Hawai"},
            {"Kalifa","Suci","P","Somalia"},
            {"Kalifa","Murni","P","Somalia"},
            {"Kalinda","Matahari","P","Hindi"},
            {"Kalyca","Kuncup bunga mawar","P","Yunani"},
            {"Kamala","Teratai","P","Sansekerta"},
            {"Kamea","Mulia","P","Hawai"},
            {"Kamini","Wanita penuh kasih sayang","P","Sansekerta"},
            {"Kanaka","Emas","P","Sansekerta"},
            {"Kanoa","Bebas","P","Hawai"},
            {"Karimah","Murah hati","P","Arab"},
            {"Kavindra","Pujangga","P","Hindi"},
            {"Kawena","Kemilau","P","Hawai"},
            {"Keiko","Anak kecil yang bahagia","P","Jepang"},
            {"Keziah","Bumbu seperti kayu manis","P","Jahudi"},
            {"khalida","Abadi","P","Arab"},
            {"Khalidah","Abadi","P","Arab"},
            {"Khamilah","Beludru","P","Arab"},
            {"Khansa","Wanita yang baik","P","Arab"},
            {"Khulud","Keabadian","P","Arab"},
            {"Kineta","Enerjik","P","Yunani"},
            {"Kostya","Tetap","P","Slavia"},
            {"Kusuma","Bunga","P","Jawa"},
            {"Kynthia","Dewi bulan","P","Yunani"},
            {"Labibah","Cerdas","P","Arab"},
            {"Lajain","Perak","P","Arab"},
            {"Lalasa","Kasih sayang","P","Hindi"},
            {"Lan","Bunga","P","Vietnam"},
            {"landra","Pembingbing","P","jerman"},
            {"Lareina","Ratu","P","Spanyol"},
            {"Lavina","Disucikan","P","latin"},
            {"Leandra","Seperti seekor singa","P","Latin"},
            {"Leilani","Bunga surga","P","Hawai"},
            {"Lianxiang","Iba dan lembut pada wanita","P","Cina"},
            {"Liqi","Menang dalam sekejab","P","Cina"},
            {"Lishan","Tenang dan kalem","P","Cina"},
            {"Lituhayu","Cantik rupawan","P","Kawi"},
            {"Lixui","Salju putih","P","Cina"},
            {"Lucretia","Kaya","P","Latin"},
            {"Luigi","Pejuang","P","Italia"},
            {"Luluah","Mutiara","P","Arab"},
            {"Luvena","Tercinta","P","Ibrani"},
            {"Mada","Kegembiraan","P","Kawi"},
            {"Magdala","Kegembiraan","P","Yunani"},
            {"Magena","Menjekang bulan purnama","P","Amerika asli"},
            {"Malca","Ratu","P","Ibrani"},
            {"Mali","Bunga melati","P","Thailand"},
            {"Malya","Rangkaian bunga","P","Kawi"},
            {"Manyari","Serangkaian bunga","P","Kawi"},
            {"Maribel","Cantik","P","Perancis"},
            {"Maritza","Mendapat berkat ilahi","P","Arab"},
            {"Marva","Bagus sekali","P","Latin"},
            {"Maxine","Yang terbesar","P","Perancis"},
            {"Maysun","Cantik","P","Arab"},
            {"Mayyadah","Yang bergoyang-goyang","P","Arab"},
            {"Meara","Riang gembira","P","Irlandia"},
            {"Medea","Memerintah","P","Yunani"},
            {"Megara","Pertama","P","Yunani"},
            {"Mehadi","Bunga","p","Hindi"},
            {"Mehri","Baik hati","p","Persia"},
            {"Mehri","Hari cerah","p","Persia"},
            {"Meiying","Bunga yang indah","p","Cina"},
            {"Melba","Lembut","p","Yunani"},
            {"Melba","Langsing","p","Yunani"},
            {"Mengda","Berpikiran cerdas","P","Cina"},
            {"Menur","Bunga melati","P","Kawi"},
            {"Meredith","Pelindung lautan","P","Wales"},
            {"Meriel","Lautan bersinar cerah","p","Irlandia"},
            {"Messina","PInggang ramping","P","Amerika asli"},
            {"Milada","Kekasihku","p","Ceko"},
            {"Mingde","Bereputasi bagus","P","Cina"},
            {"Minowa","Penyanyi","p","Amerika asli"},
            {"Moana","Aroma","p","Hawai"},
            {"Morie","Pantai","p","Jepang"},
            {"Moyna","Lembut dan halus","P","Celtik"},
            {"Mulin","Persahabatan erat","P","Cina"},
            {"Mumtazah","Lebih unggul dari yang lain","p","Arab"},
            {"Muradah","Yang dicintai","p","Arab"},
            {"Mya","Batu mulia","P","Hawai"},
            {"Nabila","Keturunan bangsawan","P","Arab"},
            {"Nadine","Penuh harapan","P","Perancis"},
            {"Najdah","Kekuatan","P","Arab"},
            {"Nalani","Seindah bunga","P","Hawai"},
            {"Nara","Bahagia","P","Yunani"},
            {"Nara","Pohon oak","P","Jepang"},
            {"Nareswari","Permaisuri","P","Sansekerta"},
            {"Nasnan","Penyanyi","P","Amerika asli"},
            {"Natha","Pelindung","P","Sansekerta"},
            {"Nathania","Pemberian Tuhan","P","Ibrani"},
            {"Nazhimah","Kumpulan mutiara","P","Arab"},
            {"Neila","Juara","P","Irlandia"},
            {"Nesha","Murni","P","Amerika asli"},
            {"Neva","Salju","P","Perancis"},
            {"Ningdei","Tenang dan anggun","P","Cina"},
            {"Nuria","Cahaya Tuhan","P","Aramaik"},
            {"Ofira","Emas","P","Yahudi"},
            {"Okalina","Surga","P","Hawai"},
            {"Olinda","Harum bunga","P","Latin"},
            {"Orea","Pegunungan","P","Yunani"},
            {"Orela","Keputasan para dewa","P","Latin"},
            {"Oriana","Matahari terbit","P","Latin"},
            {"Oriana","Waktu fajar","P","Latin"},
            {"Orlin","Berkilau keemasan","P","Yunani"},
            {"Ormanda","Bangsawan","P","Latin"},
            {"Padali","Bunga cempaka","P","Kawi"},
            {"Padmini","Wanita ulung","P","Sansekerta"},
            {"Palawa","BersemI","P","Sansekerta"},
            {"Panyun","Berprestasi tinggi","P","Cina"},
            {"Parabawa","Mencintai orang","P","Sansekerta"},
            {"Parisya","PerisaI","P","Kawi"},
            {"Pasada","Cincin","P","Sansekerta"},
            {"Pasha","Laut","p","Yunani"},
            {"Peiyu","Murni dan soleh","P","Cina"},
            {"Perlita","Mutiara","P","Italia"},
            {"Phaedra","Terang","P","Yunani"},
            {"Phalosa","Bercahaya","P","Yunani"},
            {"Purbani","Rendah sekali","P","Sansekerta"},
            {"Qabil","Cakap","P","Arab"},
            {"Qiancheng","Masa depan cerah","P","Cina"},
            {"Qionglin","Pohon salju","P","Cina"},
            {"Qisheng","Enerjik dengan suara nyaring","P","Cina"},
            {"Qixuan","Bersikap mengesankan","P","Cina"},
            {"Qujing","Kaya tujuh turunan","P","Cina"},
            {"Rabiah","Subur","P","Arab"},
            {"Rabihah","Yang beruntung","P","Arab"},
            {"Radella","Penasihat","P","Jerman"},
            {"Radinka","Senang","P","Slavia"},
            {"Rafa","Bahagia","P","Arab"},
            {"Rafa","Kaya raya","P","Arab"},
            {"Raina","Maha perkasa","P","Jerman"},
            {"Ramaniya","Menyenangkan","P","Sansekerta"},
            {"Ransi","Berotak brilian","P","Cina"},
            {"Rashida","Keadilan","P","Turki"},
            {"Rasiyah","Yang tegar","P","Arab"},
            {"Ratana","Kristal","P","Thailand"},
            {"Ratnamaya","Bertahtakan permata","P","Sansekerta"},
            {"Reseda","Aroma bunga","P","Spanyol"},
            {"Reyhan","Bunga yang aromanya wangi","P","Turki"},
            {"Ridong","Prestasi dan andil besar","P","Cina"},
            {"Rika","Penguasa","P","Swedia"},
            {"Rongdan","Berwajah cantik","P","Cina"},
            {"Ronghui","Memahami masalah","P","Cina"},
            {"Roselani","Bunga mawar surga","P","Hawai"},
            {"Ruhua","Muda dan cantik","P","Cina"},
            {"Rukmi","Emas","P","Kawi"},
            {"Sabiya","PagI hari","P","Arab"},
            {"Sadara","Terhormat","P","Sansekerta"},
            {"Sadira","Bintang","P","Arab"},
            {"Sakinah","Berwibawa","P","Arab"},
            {"Salaga","Kuncup bunga","P","Kawi"},
            {"Salimah","Yang terhindar dari kejelekan","P","Arab"},
            {"Salvia","Bibit","P","Latin"},
            {"Samara","Benih pohon","P","Latin"},
            {"Samira","Batu mulia","P","Arab"},
            {"Sarila","Air terjun","P","Turki"},
            {"Sashuang","Berani dan berjiwa pahlawan","P","Cina"},
            {"Saskia","Pelindung Manusia","P","Hawai"},
            {"Selena","Bulan","P","Yunani"},
            {"Selma","Pelindung suci","P","Jerman"},
            {"Sewagati","Pengabdian","P","Sansekerta"},
            {"Shabirah","Yang bersabar","P","Arab"},
            {"Shafira","Istimewa","P","Swahili"},
            {"Shafiyah","Jernih","P","Arab"},
            {"Shahia","Mata yang indah","P","Afganistan"},
            {"Shanmimg","Pemandangan inmdah","P","Cina"},
            {"Shatara","Payung","P","Hindi"},
            {"Shatara","Ramah tamah","P","Arab"},
            {"Shira","Nyanyian","P","Yahudi"},
            {"Shira","Kesejahteraan","P","Ibrani"},
            {"Shula","Bercahaya","P","Arab"},
            {"Shuoxue","Berkemauan belajar sangat Giat","P","Cina"},
            {"Shuwan","Berhati mulia dan periang","P","Cina"},
            {"Sidra","Anak bintang","P","Latin"},
            {"Silawarti","Berkelakuan baik","P","Sansekerta"},
            {"Speranza","Harapan","P","Italia"},
            {"Stina","Disucikan","P","Jerman"},
            {"Sumina","Bercahaya","P","Kawi"},
            {"Sunee","Baik hati","P","Thailand"},
            {"Suniyyah","Yang bersinar","P","Arab"},
            {"Syauq","Kerinduan","P","Arab"},
            {"Syua","Rembulan","P","Arab"},
            {"Tabia","Berbakat","P","Swahili"},
            {"Tabina","Pengikut Nabi Muhammad SAW","P","Arab"},
            {"Tabitha","Kijang","P","Yunani"},
            {"Tadita","Pelari","P","Omaha"},
            {"Talidah","Klasik","P","Arab"},
            {"Talitha","Gadis muda belia","P","Arab"},
            {"Tansy","Abadi","P","Yunani"},
            {"Tansy","Tekun","P","Latin"},
            {"Taraka","Bermata bintang","P","Kawi"},
            {"Tasanee","Cantik","P","Thailand"},
            {"Tawaddud","Cinta kasih","P","Arab"},
            {"Tertia","Ketiga","P","Latin"},
            {"Tevy","Malaikat","P","Kamboja"},
            {"Theona","Anugerah Tuhan","P","Yunani"},
            {"Tianba","Hebat tiada tara","P","Cina"},
            {"Tianzhi","Bersumpah atas nama surga","P","Cina"},
            {"Tongcai","Orang pintar","P","Cina"},
            {"Tsabitah","Pemberrani","P","Arab"},
            {"Tuyen","Malaikat","P","Vietnam"},
            {"Ulani","Riang gembira","P","Polinesia"},
            {"Ulfah","Pemberani","P","Arab"},
            {"Ulima","Kebijaksanaan","P","Arab"},
            {"Umeko","Sabar","P","Jepang"},
            {"Ummiyah","Harapan","P","Arab"},
            {"Vala","Yang terpilih","P","Jerman"},
            {"Valerie","Kuat","P","Latin"},
            {"Vega","Bintang jauh","P","Arab"},
            {"Verda","Muda","P","Arab"},
            {"Verda","Segar","P","Arab"},
            {"Vondro","Wanita yang menarik","P","Ceko"},
            {"Wagindra","Bahasanya baik","P","Kawi"},
            {"Waiduri","Permata","P","Indonesia"},
            {"Wastiqah","Yang benar","P","Arab"},
            {"Widati","Berhati harum","P","Jawa"},
            {"Wikrama","Keteguhan hati","P","Sansekerta"},
            {"Winda","Pemburu","P","Swahili"},
            {"Winna","Sahabat","P","Afrika"},
            {"Winola","Sahabat yang menawan","P","Jerman"},
            {"Winona","Anak tertua","P","Lakota"},
            {"Xianlun","Sopan dan cantik","P","Cina"},
            {"Xinxin","Berkembang dan maju","P","Cina"},
            {"Xionglue","Punya bakat bagus dan visi luas","P","Cina"},
            {"Yichang","Berkembang dan makmur","P","Cina"},
            {"Yihua","Berpenampilan menarik","P","Cina"},
            {"Yiran","Penuh minat dan selera","P","Cina"},
            {"Yizhen","Kemampuan belajar giat","P","Cina"},
            {"Yocelyn","Riang gembira","P","Amerika asli"},
            {"Yogini","Petapa wanita","P","Sansekerta"},
            {"Yueyin","Sinar bulan terang","P","Cina"},
            {"Zahirah","Bercahaya","P","Arab"},
            {"Zakiyah","Yang baik","P","Arab"},
            {"Zamira","Nyanyian","P","Ibrani"},
            {"Zebediah","Anugerah Tuhan","P","Ibrani"},
            {"Zhabyah","Kijang betina","P","Arab"},
            {"Zhilin","Murid terkemuka","P","Cina"},
            {"Zhiping","Disukai Tuhan","P","Cina"},
            {"Zhishu","Terdidik dan baik budi","P","Cina"},
            {"Zita","Kekasih yang terhormat","P","Ibrani"},
            {"Zongheng","Berpostur tinggi","P","Cina"}
    };
}
